title: Elisabeth Matthews
description: Astrophysicist
logo: images/matthews2018.png
address1: she/her <br>
address2: Max-Planck-Institut für Astronomie 
address3: Königstuhl 17 
address4: 69117 Heidelberg, Germany <br>
email: matthews@mpia.de
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
